### ISSUE TITLE
Parallel

### ISSUE THREAD

**Issue by emilyb7** [FAC-11/week3-TAAA#44]
Yay, glad to see you attempted this : ) I haven't cloned your repo so I don't know for sure that your code is all working but it looks good.

You could probs improve the naming of your functions and variables.

For example, on line 40 you have `parallel(result)`

Parallel is a very generic function name. Think about what your function is doing in your case. Maybe something like `getYoutubeResultsInParallel` would be better? And you could call `result` something like `tflResultsArray`.

**Comment by morkeltry** [comment]
> Yay, glad to see you attempted this : ) I haven't cloned your repo so I don't know for sure that your code is all working but it looks good.

Guess you'll have to watch the demo, then ;)
